# header nav
# 菜单路径
menu:
  home: /
  archives: archives
  tags: tags
  about: about
  search: search

# site title 
# 页面的标题
# title为空时 Hexo/_config.yml 配置有效
title: 

# author profile
# source/imgaes/
# 作者信息
# author为空时 Hexo/_config.yml 配置有效
profile: 
  author: Lizy
  avatar: /images/local-logo.png  
  description: 

# site favicon
# source/imgaes/
# 站点图标
favicon: /images/favicon.png

# social link
social:  
#   Github: https://github.com/Lemonreds/hexo-theme-nayo 
#   Weibo:
# # Zhihu:
#   Facebook:
#   Twitter:
#   Instagram:
#   LinkedIn:


# toc
# 文章的目录 
toc:
    true

# site analytics 
# 站点访问统计
# [ analytics id ]
baidu_analytics:

google_analytics: 
  UA-121998627-1
# comment

# disqus(https://disqus.com/)
disqus:
  comment: true
  shortname: lemonreds

# valine(https://github.com/xCss/Valine)
# 创建 leancloud 应用 获取 id|key 填入即可
leancloud:  
  comment: false
  app_id: 
  app_key: 

# mob share(http://www.mob.com)
# 文章分享功能
mob_share:
  true

share_item:
- qq
- weixin
- weibo
- douban
- facebook
- twitter
#- tumblr
# - google


# donate
# 捐赠功能
# source/imgaes/
donate:
  enable: false
  word: 世界美好 你也是
  wechat: 
  alipay: 

# mathjax 
# 渲染LateX公式
# 在post文章头部添加:
#   mathjax: true
# 即可在当前post开启mathjax
mathjax:
  enable: true
  
# excerpt_ignore [boolean]
# increase at the top of your article
# Does this article need to hide the excerpt ?
# 在文章头部中增加此配置 
# 文章是否需要显示摘要 默认为显示

# footer
# 底部信息
footer:
  author: Lizy
  since: 2018


# theme version
#
version:
  0.3.0